export default function Home() {
  return (
    <main className="min-h-screen bg-black text-white">

      {/* Hero */}
      <section className="flex flex-col items-center justify-center h-screen text-center">
        <h1 className="text-5xl font-bold mb-4">
          AI Interview Simulator
        </h1>

        <p className="text-gray-400 mb-6">
          Practice real interviews with AI and get instant feedback.
        </p>

        <button className="bg-blue-600 px-6 py-3 rounded-lg">
          Start Interview
        </button>
      </section>

      {/* Features */}
      <section className="py-20 px-10 grid md:grid-cols-3 gap-6">
        <div className="bg-gray-900 p-6 rounded-xl">
          <h3 className="text-xl font-semibold mb-2">
            AI Generated Questions
          </h3>
          <p className="text-gray-400">
            Practice with dynamic questions generated by AI.
          </p>
        </div>

        <div className="bg-gray-900 p-6 rounded-xl">
          <h3 className="text-xl font-semibold mb-2">
            Instant Feedback
          </h3>
          <p className="text-gray-400">
            Get detailed feedback on every answer.
          </p>
        </div>

        <div className="bg-gray-900 p-6 rounded-xl">
          <h3 className="text-xl font-semibold mb-2">
            Progress Tracking
          </h3>
          <p className="text-gray-400">
            Track improvement across interviews.
          </p>
        </div>
      </section>

    </main>
  )
}